/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {

    Library testLib = new Library();

    @Test public void testRollMethod() {

        int rollAmt = 4;
        int[] resultArray = testLib.roll(rollAmt);
        // test to make sure the length is the amount specified by input
        assertTrue(rollAmt == resultArray.length);
        // test to make sure elements are values from 1 to 6 inclusive.
        for (int rollValue : resultArray) {
            assertTrue(rollValue > 0 && rollValue < 7);
        }
    }

    @Test public void testContainsDuplicates() {

        int[] testArrayNoDuplicates = new int[]{1, 2, 3, 4, 5};
        boolean falseResult = testLib.containsDuplicates(testArrayNoDuplicates);
        assertFalse(falseResult);

        int[] testArrayDuplicates = new int[]{1, 2, 3, 4, 5, 3};
        boolean trueResult = testLib.containsDuplicates(testArrayDuplicates);
        assertTrue(trueResult);
    }

    @Test public void testAverageOfArrayValues() {

        int[] testArray = new int[]{2, 4, 6, 8, 10};
        double averageResult = testLib.averageOfArrayValues(testArray);
        assertEquals(6.0, averageResult, 0.001);
    }

    @Test public void testLowestAverageOfArrayofArraysValues() {

        int[][] testArray = {
                {66, 64, 58, 65, 71, 57, 60}, // avg 63
                {57, 65, 65, 70, 72, 65, 51}, // avg 63.5
                {55, 54, 60, 53, 59, 57, 61}, // avg 57
                {65, 56, 55, 52, 55, 62, 57}  // avg 57.4
        };

        int[] expectedArray = new int[]{55, 54, 60, 53, 59, 57, 61};
        int[] resultArray = testLib.arrayOfLowestAvgOfArrayOfArrays(testArray);

        assertArrayEquals(expectedArray, resultArray);



    }

}
