/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

public class Library {

    public int[] roll(int rollAmt) {

        int[] resultOfRolls = new int[rollAmt];

        for (int i = 0; i < resultOfRolls.length; i++) {

            int randoNum = (int)(Math.random() * 6) + 1;
            resultOfRolls[i] = randoNum;
        }

        return resultOfRolls;
    }

    public boolean containsDuplicates(int[] inputArray) {

        boolean flag = false;

        for (int i = 0; i < inputArray.length; i++) {

            for (int j = i + 1; j < inputArray.length; j++) {

                if (inputArray[i] == inputArray[j]) {
                    flag = true;
                }
            }
        }
        return flag;
    }

    public double averageOfArrayValues(int[] inputArray) {

        double arrayValueTotal = 0;

        for (int value : inputArray) {
            arrayValueTotal += value;
        }

        return arrayValueTotal / inputArray.length;
    }

    public int[] arrayOfLowestAvgOfArrayOfArrays(int[][] inputArrays) {

        int lowestAverageArrayIndex = 0;
        double lowestAverage = 100000000.0;

        for (int i = 0; i < inputArrays.length; i++) {

            for (int j = 0; j < inputArrays.length; j++) {

                double nextAvg = averageOfArrayValues(inputArrays[j]);
                if (nextAvg < lowestAverage) {
                    lowestAverage = nextAvg;
                    lowestAverageArrayIndex = j;
                }
            }
        }
        return inputArrays[lowestAverageArrayIndex];
    }

}
